### ISSUE TITLE
Does not work for WAITING tasks

### ISSUE THREAD

**Issue by duckunix** [voidcase/taskseq#1]
Have not had a chance to look at the code, but it throws the following when trying to run against list of tasks where are waiting:

```
Traceback (most recent call last):
  File "/home/don/.local/bin/taskseq", line 8, in <module>
    sys.exit(run())
  File "/home/don/.local/lib/python3.8/site-packages/taskseq.py", line 49, in run
    tw.task_update(depender)
  File "/usr/lib/python3/dist-packages/taskw/warrior.py", line 798, in task_update
    self._execute(task_uuid, 'modify', *modification)
  File "/usr/lib/python3/dist-packages/taskw/warrior.py", line 476, in _execute
    raise TaskwarriorError(command, stderr, stdout, proc.returncode)
taskw.exceptions.TaskwarriorError: <exception str() failed>
```

It does work for tasks which are not hidden due to waiting.

**Comment by voidcase** [comment]
Thanks for reporting!
I have been able to reproduce the bug but I don't understand why it's happening yet.
